### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by gjorgic** [plavatvornica/cc#36]
potrebno je kreirati branch ```homepage-fix``` iz brancha ```faza-01```

u njemu je potrebno odraditi sljedeće taskove

## Važno!!!
Molim da se pridržava [pravila za rad sa gitom](https://github.com/gjorgic/cc/issues/37)
Nakon završetka napraviti push na svoj forkani repozitorij:
> ``` git push <your-forked-repo-remote> homepage-fix:homepage-fix ```

Zatim uraditi pull request iz ```homepage-fix/your-forked-repo``` u ```faza-01/cc```

# Tasks
- [x]  <b>Nedostaje putujući box kao prečac za tvrtke</b>

> dodati box kao što je u dizajnu <strike>koji će putovati prema dolje kako korisnik bude scrollao, te nestati kad korisnik dođe do zadnje sekcije koja je</strike> i kad se klikne na link "saznaj više" unutar boxa - prebacimo korisnika skroz na dno stranice gdje je sekcija namjenjena za tvrtke
 
> URL: http://cc.devtvornica.org/
> PRTSCN: http://prntscr.com/bscqal
> Assign to: @nikolakrivokapic 
***
> <b>Smjernice</b>
> nije potrebno kreirati komponentu; sass se treba odraditi u sasu od homepagea;
> SASS nemoj te ga nestati;

- [x]  <b>Umjesto dnevnik karijere treba pisati Tvrtke i škole</b>

> Vidi screenshot gdje je greška desno
 
> URL: http://cc.devtvornica.org/
> PRTSCN: http://prntscr.com/bsdy4m
> Assign to: @nikolakrivokapic 
***
> <b>Smjernice</b>
>

- [x]  <b>Nedostaje pozadinska slika u zadnjoj sekciji</b>

> Vidi screenshot iz dizajna desno
 
> URL: http://cc.devtvornica.org/
> PRTSCN: http://prntscr.com/bsdyq0
> Assign to: @erklat 
***
> <b>Smjernice</b>
>

- [x]  <b>Spacing</b>

> Potrebno dodati razmak i da ide u novi red
 
> URL: http://cc.devtvornica.org/
> PRTSCN: http://prntscr.com/bsdz9d
> Assign to: @nikolakrivokapic 
***
> <b>Smjernice</b>
>

- [x]  <b>Tekst na buttonu</b>

> Nije Kreiraj oglas nego je OBJAVI NATJEČAJ
 
> URL: http://cc.devtvornica.org/
> PRTSCN: http://prntscr.com/bse08n
> Assign to: @nikolakrivokapic 
***
> <b>Smjernice</b>
>

- [x]  <b>Hover efekt na Korisnici/Tvrtke i škole u footeru više izgleda kao efekt stroboskop-a</b>

> Napraviti da bude blaži taj efekt
 
> URL: http://cc.devtvornica.org/
> PRTSCN: http://prntscr.com/bse1v3
> Assign to: @erklat 
***
> <b>Smjernice</b>
>

**Comment by gjorgic** [comment]
ovaj dio sa Hover efektom će riješiti @erklat 
a dio sa slikom ću ja kad se vratim sa GO

**Comment by erklat** [comment]
Vidi za ovaj zadnji task jel bolje ovako, inače moramo napraviti još dva asseta jer se promjena background positiona također animira, a kako u svg-u nisu ikonice dobro poredan, vidjet će se tranzicija preko ikonica koje ne pripadaju tu.

**Comment by gjorgic** [comment]
reći ću davoru da ovo riješi pa da zatvorim, dakle matej je rekao da se icone na hover mjenjaju bez animacije

**Comment by gjorgic** [comment]
riješen je i dio sa ikonama, dakle sad su bez animacije
